#!/bin/bash
set -e 

chown "${DEPLOY_USER}:${DEPLOY_USER}" -R "${DEPLOY_USER_DIR}"

su "${DEPLOY_USER}"  -s /bin/bash -c "\
    pushd ${DEPLOY_USER_DIR}/django-hatstall && \
    echo 'Fill the secret key, allow hosts'
    python3 config_deployment.py && \
    echo 'Create the data models' && \
    python3 manage.py makemigrations && \
    python3 manage.py migrate && \
    python3 manage.py collectstatic --noinput && \
    echo 'Create the initial admin user: admin/admin' && \
    PYTHONPATH=. django_hatstall/create_admin_superuser.py
    "

# Run the Hatstall service with apache2 + mod_wsgi
echo "Running Hatstall"
chown -R www-data "${DEPLOY_USER_DIR}"
apachectl -D FOREGROUND
